Feature/popups for creating user and connection
MishaHnatyshyn/Datalyzer pull request #17
Opened 2019-12-11 23:13 UTC by delieva

Everything is done excepting rerender count of users/connections and table/grid after successful creation

2019-12-13 12:18 UTC, VladaZhmurkevych requested changes

2019-12-13 12:18 UTC, VladaZhmurkevych commented on src/components/User/newUserPopup/newUserPopup.module.scss
> +  font: normal 18px "Montserrat";
We have variables for fonts, so it is no needed to write this by yourself. Is there is no font-size which is needed for you, it is better to use a variable, which sets you font-bold and font-family, and write here font-size by yourself

2019-12-13 12:18 UTC, VladaZhmurkevych commented on src/components/User/newUserPopup/newUserPopup.module.scss
> +  -moz-appearance: none;
We have autoprefixer, so you do need to write this

2019-12-13 12:18 UTC, VladaZhmurkevych commented on src/components/shared/BasePopup/index.js
> +      <div className={classnames(styles.popupWrapper, popupClassName)}>
I can't find popupClassName. Where is it declared?

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/store/createUser/reducer.js
> +  users: [],
Remove these fields, expects error from createUser reducer as it does not relate to creating user logic

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/store/createUser/reducer.js
> +        },
move this logic to adminUsers reducer and leave here only cleaning of form

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/store/connectionForm/reducer.js
> +        hasNextPage: action.payload.length > 0,
move this logic to connections reducer and leave here only form cleaning

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/store/connectionForm/actions.js
> +    dispatch(onCloseAction());
What does it do ?

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/store/connection/reducer.js
> +        connections: [...state.connections, action.payload],
I believe we should add new conenction to the start of list: `connections: [ action.payload, ...state.connections],`

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/store/connection/actions.js
> +    dispatch(push('/admin/databases'));
Why do we need this ?

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/store/adminUsers/reducer.js
>          formPasswordRepeat: '',
remove this logic from here

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/store/adminUsers/reducer.js
> +        users: [action.payload, state.users],
`users: [action.payload, ...state.users],`

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/store/adminUsers/reducer.js
> +  isVisible: true,
remove this from here

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/pages/page.js
> +export default UsersAdmin;
what is this ?

2019-12-13 12:29 UTC, MishaHnatyshyn commented on src/components/User/newUserPopup/newUserPopup.module.scss
> +}
This file is almost the same as newDBConnectionPopup.module.scss.

2019-12-13 15:19 UTC, delieva commented on src/components/shared/BasePopup/index.js
> +      <div className={classnames(styles.popupWrapper, popupClassName)}>
It`s a prop

2019-12-13 15:38 UTC, VladaZhmurkevych commented on src/components/shared/BasePopup/index.js
> +      <div className={classnames(styles.popupWrapper, popupClassName)}>
okay, thanks :)

2019-12-14 16:59 UTC, VladaZhmurkevych requested changes

2019-12-14 16:59 UTC, VladaZhmurkevych commented on src/components/User/newUserPopup/NewUserForm/index.js
> +import '../../../shared/BasePopup/styles.scss';
You shouldn't import styles from other components.

2019-12-14 16:59 UTC, VladaZhmurkevych commented on src/components/User/newUserPopup/NewUserForm/index.js
> +        </select>
use, please, Select component from 'shared'

2019-12-14 16:59 UTC, VladaZhmurkevych commented on src/components/User/newUserPopup/index.js
> +import '../../shared/BasePopup/styles.scss';
the same, don't import these styles

2019-12-14 16:59 UTC, VladaZhmurkevych commented on src/components/newDBConnectionPopup/NewDBConnectionForm/index.js
> +import '../../shared/BasePopup/styles.scss';
same here

2019-12-14 16:59 UTC, VladaZhmurkevych commented on src/components/shared/BasePopup/components/PopupButton/popupButton.module.scss
> +  margin: 0 44px;
Won't it affect other popups?

2019-12-15 10:12 UTC, VladaZhmurkevych commented on src/components/Login/LoginForm/index.js
> +          <Input text="Password" type="password" withImage classes="withImage" onChange={changePassword} value={password}>
why do you need `classes withImage`?

2019-12-15 10:13 UTC, VladaZhmurkevych requested changes

2019-12-15 10:13 UTC, VladaZhmurkevych commented on src/components/User/newUserPopup/NewUserForm/index.js
> +        <Select options={[{ name: 'admin', value: '1' }, { name: 'user', value: '2' }]} classes={styles.select} value={formUserType} onChange={changeUserType} />
move options value to variable

2019-12-15 10:15 UTC, VladaZhmurkevych commented on src/components/newDBConnectionPopup/NewDBConnectionForm/index.js
> +          <Select options={[{ name: 'PostgreSQL', value: '1' }]} classes={styles.select} value={type} onChange={changeType} />
the same, move to the variable

2019-12-15 11:24 UTC, VladaZhmurkevych approved these changes

2019-12-15 11:25 UTC, merged